name: Pull request closed
on:
    pull_request:
        types: [closed]

concurrency:
    group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    remove-image:
        name: Remove Docker image
        if: github.event.pull_request.merged == false
        runs-on: ubuntu-22.04
        timeout-minutes: 5
        steps:
            - name: Checkout repo
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Remove pr-${{ github.event.pull_request.number }} image
              uses: ./.github/actions/remove-image
              with:
                  namespace: ${{ secrets.DH_USERNAME }}
                  repository: ${{ github.event.repository.name }}
                  tag: pr-${{ github.event.pull_request.number }}
                  token: ${{ secrets.DH_READ_WRITE_DELETE }}
                  username: ${{ secrets.DH_USERNAME }}
